### ISSUE TITLE
push_proposal: double free or corruption while replaying 

### ISSUE THREAD

**Issue by abitmore** [abitmore/bitshares-2#3]
```
1722983ms th_a       db_block.cpp:267              push_proposal        ] push_proposal {"id":"1.10.0","expiration_time":"2016-02-11T15:29:00","review_period_time":"2016-02-11T15:28:30","proposed_transaction":{"ref_block_num":0,"ref_block_prefix":0,"expiration":"2016-02-11T15:29:00","operations":[[45,{"fee":{"amount":100000,"asset_id":"1.3.0"},"new_options":"max_supply":100000,"market_fee_percent":10,"max_market_fee":"1000000000000000","issuer_permissions":0,"flags":0,"core_exchange_rate":{"base":{"amount":0,"asset_id":"1.3.0"},"quote":{"amount":0,"asset_id":"1.3.0"}},"whitelist_authorities":[],"blacklist_authorities":[],"whitelist_markets":[],"blacklist_markets":[],"description":"","extensions":[]},"extensions":[]}]],"extensions":[]},"required_active_approvals":["1.2.0"],"available_active_approvals":["1.2.6","1.2.7","1.2.8","1.2.9","1.2.10","1.2.11","1.2.12","1.2.13","1.2.14","1.2.15"],"required_owner_approvals":[],"available_owner_approvals":[],"available_key_approvals":[]}, before remove, eval_state.op_results=[[0,{}]]
1722983ms th_a       index.hpp:277                 remove               ] remove {"id":"1.10.0"}
1722983ms th_a       index.hpp:280                 remove               ] on remove {"id":"1.10.0"}
1722983ms th_a       index.hpp:282                 remove               ] der remove {"id":"1.10.0"}
1722983ms th_a       index.hpp:284                 remove               ] der removed {"id":"0.0.140737336874936"}
1722983ms th_a       db_block.cpp:269              push_proposal        ] push_proposal removed, session=(s)
1722983ms th_a       undo_database.cpp:127         merge                ] _stack.size=1
1722983ms th_a       db_block.cpp:285              push_proposal        ] 10 assert_exception: Assert Exception
_stack.size() >=2:
    {}
    th_a  undo_database.cpp:128 merge

*** Error in `/app/bts/bts2-test-pct-transfer-fee-debug/programs/witness_node/witness_node': double free or corruption (out): 0x000000
0005b05600 ***

Program received signal SIGABRT, Aborted.
0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6c01cc9 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6c050d8 in __GI_abort () at abort.c:89
#2  0x00007ffff6c3e394 in __libc_message (do_abort=do_abort@entry=1,
    fmt=fmt@entry=0x7ffff6d4cb28 "*** Error in `%s': %s: 0x%s ***\n") at ../sysdeps/posix/libc_fatal.c:175
#3  0x00007ffff6c4a66e in malloc_printerr (ptr=<optimized out>, str=0x7ffff6d4cc58 "double free or corruption (out)", action=1)
    at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x000000000218ba4a in __gnu_cxx::new_allocator<fc::variant>::deallocate (this=0x5b07ac0, __p=0x5b05600)
    at /usr/include/c++/4.8/ext/new_allocator.h:110
#6  0x000000000218b59e in std::_Vector_base<fc::variant, std::allocator<fc::variant> >::_M_deallocate (this=0x5b07ac0,
    __p=0x5b05600, __n=57) at /usr/include/c++/4.8/bits/stl_vector.h:174
#7  0x000000000218a957 in std::_Vector_base<fc::variant, std::allocator<fc::variant> >::~_Vector_base (this=0x5b07ac0,
    __in_chrg=<optimized out>) at /usr/include/c++/4.8/bits/stl_vector.h:160
#8  0x00000000021899e5 in std::vector<fc::variant, std::allocator<fc::variant> >::~vector (this=0x5b07ac0, __in_chrg=<optimized out>)
    at /usr/include/c++/4.8/bits/stl_vector.h:416
#9  0x0000000002875122 in fc::variant::clear (this=0x5b07580)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/fc/src/variant.cpp:177
#10 0x000000000287532e in fc::variant::operator=(fc::variant&&) (this=0x5b07580,
    v=<unknown type in /app/bts/bts2-test-pct-transfer-fee-debug/programs/witness_node/witness_node, CU 0x53f06b8, DIE 0x541264a>)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/fc/src/variant.cpp:226
#11 0x00000000022878b9 in fc::to_variant<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object> > (var=..., vo=...) at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/fc/include/fc/container/flat.hpp:66
#12 0x000000000227e90b in fc::variant::variant<boost::container::flat_set<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object>, std::less<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object> >, std::allocator<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object> > > > (
    this=0x7fffffffac70, val=...) at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/fc/include/fc/variant.hpp:528
#13 0x0000000002273db4 in fc::mutable_variant_object::operator()<boost::container::flat_set<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object>, std::less<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object> >, std::allocator<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object> > > const&> (this=0x7fffffffad60,
    key="@\253\377\377\377\177\000\005ຳ\005\000\000\000\000@\253\377\377\377\177\000\005\060\273\263\005\000\000\000\000@\253\377\377\377\177\000\005\200\273\263\005\000\000\000\000@\253\377\377\377\177\000\005л\263\005\000\000\000\000@\253\377\377\377\177\000\005\274\263\005\000\000\000\000@\253\377\377\377\177\000\005p\274\263\005\000\000\000\000@\253\377\377\377\177\000\005\300\274\263\005\000\000\000\000@\253\377\377\377\177\000\005\020\275\263\005\000\000\000\000@\253\377\377\377\177\000\005`\275\263\005\000\000\000\000@\253\377\377\377\177\000\005\260\275\263\005\000\000\000\000@\253\377\377\377\177\000\005\000\276\263\005\000\000\000\000@\253\377\377\377\177\000\005P\276\263\005\000\000\000\000@\253\377\377\377\177\000\005"..., var=...)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/fc/include/fc/variant_object.hpp:176
#14 0x00000000022772f9 in fc::to_variant_visitor<graphene::chain::proposal_object>::add<boost::container::flat_set<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object>, std::less<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object> >, std::allocator<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object> > > > (this=0x7fffffffad70, vo=..., name=0x2d3516f "required_active_approvals", v=...)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/fc/include/fc/reflect/variant.hpp:35
#15 0x000000000226cbfa in fc::to_variant_visitor<graphene::chain::proposal_object>::operator()<boost::container::flat_set<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object>, std::less<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object> >, std::allocator<graphene::db::object_id<(unsigned char)1, (unsigned char)2, graphene::chain::account_object> > >, graphene::chain::proposal_object, &graphene::chain::proposal_object::required_active_approvals> (
    this=0x7fffffffad70, name=0x2d3516f "required_active_approvals")
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/fc/include/fc/reflect/variant.hpp:23
#16 0x000000000226160b in fc::reflector<graphene::chain::proposal_object>::visit<fc::to_variant_visitor<graphene::chain::proposal_object> > (v=...) at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/chain/include/graphene/chain/proposal_object.hpp:90
#17 0x0000000002255ff1 in fc::if_enum<fc::false_type>::to_variant<graphene::chain::proposal_object> (v=..., vo=...)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/fc/include/fc/reflect/variant.hpp:67
#18 0x0000000002242786 in fc::to_variant<graphene::chain::proposal_object> (o=..., v=...)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/fc/include/fc/reflect/variant.hpp:100
#19 0x0000000002232f5b in fc::variant::variant<graphene::chain::proposal_object> (this=0x7fffffffb330, val=...)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/fc/include/fc/variant.hpp:528
#20 0x0000000002563163 in graphene::chain::database::push_proposal (this=0x5ace278, proposal=...)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/chain/db_block.cpp:291
#21 0x000000000258d0c6 in graphene::chain::database::clear_expired_proposals (this=0x5ace278)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/chain/db_update.cpp:176
#22 0x0000000002568b41 in graphene::chain::database::_apply_block (this=0x5ace278, next_block=...)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/chain/db_block.cpp:522
#23 0x0000000002567dc8 in graphene::chain::database::__lambda19::operator() (__closure=0x7fffffffb9e0)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/chain/db_block.cpp:478
#24 0x000000000259172f in graphene::chain::detail::with_skip_flags<graphene::chain::database::apply_block(const graphene::chain::signed_block&, uint32_t)::__lambda19>(graphene::chain::database &, uint32_t, graphene::chain::database::__lambda19) (db=...,
    skip_flags=1127, callback=...)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/chain/include/graphene/chain/db_with.hpp:126
#25 0x00000000025681df in graphene::chain::database::apply_block (this=0x5ace278, next_block=..., skip=1127)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/chain/db_block.cpp:479
#26 0x000000000257c510 in graphene::chain::database::reindex (this=0x5ace278, data_dir=..., initial_allocation=...)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/chain/db_management.cpp:92
#27 0x00000000021a141a in graphene::app::detail::application_impl::startup (this=0x5ace140)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/app/application.cpp:340
#28 0x0000000002192d3c in graphene::app::application::startup (this=0x5acded0)
    at /app/bts/bts2-test-pct-transfer-fee-debug/libraries/app/application.cpp:968
#29 0x0000000002168dad in main (argc=34, argv=0x7fffffffde98)
    at /app/bts/bts2-test-pct-transfer-fee-debug/programs/witness_node/main.cpp:161

```

**Comment by abitmore** [comment]
First time when the proposal executes:
```
300002ms th_a       db_block.cpp:267              push_proposal        ] push_proposal {"id":"1.10.0","expiration_time":"2016-02-11T22:05:00","review_period_time":"2016-02-11T22:04:30","proposed_transaction":{"ref_block_num":0,"ref_block_prefix":0,"expiration":"2016-02-11T22:05:00","operations":[[45,{"fee":{"amount":100000,"asset_id":"1.3.0"},"new_options":{"max_supply":100000,"market_fee_percent":10,"max_market_fee":"1000000000000000","issuer_permissions":0,"flags":0,"core_exchange_rate":{"base":{"amount":0,"asset_id":"1.3.0"},"quote":{"amount":0,"asset_id":"1.3.0"}},"whitelist_authorities":[],"blacklist_authorities":[],"whitelist_markets":[],"blacklist_markets":[],"description":"","extensions":[[1,{"transfer_fee_mode":"asset_transfer_fee_mode_percentage_simple"}]]},"extensions":[]}]],"extensions":[]},"required_active_approvals":["1.2.0"],"available_active_approvals":["1.2.6","1.2.7","1.2.8","1.2.9","1.2.10","1.2.11","1.2.12","1.2.13","1.2.14","1.2.15"],"required_owner_approvals":[],"available_owner_approvals":[],"available_key_approvals":[]}, before remove, eval_state.op_results=[[0,{}]]
300002ms th_a       index.hpp:277                 remove               ] remove {"id":"1.10.0"}
300002ms th_a       index.hpp:280                 remove               ] on remove {"id":"1.10.0"}
300002ms th_a       index.hpp:282                 remove               ] der remove {"id":"1.10.0"}
300002ms th_a       index.hpp:284                 remove               ] der removed {"id":"0.0.140737336874936"}
300002ms th_a       db_block.cpp:269              push_proposal        ] push_proposal removed, session=(s)
300002ms th_a       undo_database.cpp:127         merge                ] _stack.size=11
300002ms th_a       db_block.cpp:271              push_proposal        ] push_proposal session merged, session=(s)
```
